highlight_symbol = "|"
api = "local"
tabs = ["videos", "streams"]
refresh_threshold = 0
rss_threshold = 9999
subtitle_languages = ["en", "tr"]
video_quality = "2160p"

focused = { fg = "Magenta", bg = "Black", modifiers = "bold" }
selected_block = { fg = "Magenta", modifiers = "bold" }
error = { fg = "Red", modifiers = "italic" }

[key_bindings]
"p" = "play_from_formats"
"P" = "play_video"
