highlight_symbol = "|"
api = "local"
tabs = ["videos", "streams"]
refresh_threshold = 0
subtitle_languages = ["en", "tr"]
video_quality = "2160p"
preferred_video_codec = "webm"
preferred_audio_codec = "webm"

focused = { fg = "Magenta", bg = "Black", modifiers = "bold" }
error = { fg = "Red", modifiers = "italic" }
